
-- USER
INSERT INTO KPN_PCPL (ID, NAME, ENABLED, PRINCIPAL_TYPE) VALUES (1, 'root', TRUE, 0);
INSERT INTO KPN_PCPL (ID, NAME, ENABLED, PRINCIPAL_TYPE) VALUES (2, 'GROUP ADMINISTRATOR', TRUE, 1);
INSERT INTO KPN_USER (ID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, PASSWORD, EXPIRED, LOCKED)
VALUES (1, 'ROOT', 'KPN BTM', '0123456789', 'root@kpn.gov.my', 'abc123', FALSE, FALSE);
INSERT INTO KPN_PCPL_ROLE (ID, PRINCIPAL_ID, ROLE_TYPE) VALUES(1, 1, 0);
INSERT INTO KPN_PCPL_ROLE (ID, PRINCIPAL_ID, ROLE_TYPE) VALUES(2, 1, 1);

-- GROUP
INSERT INTO KPN_GROP (ID) VALUES (2);
INSERT INTO KPN_GROP_MMBR (ID, GROUP_ID, USER_ID) VALUES (1, 2, 1);



