
-- USER
INSERT INTO KPN_PCPL (ID, NAME, ENABLED, LOCKED, PRINCIPAL_TYPE, M_ST, C_ID, C_TS) VALUES (1, 'root', TRUE, FALSE, 0, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO KPN_PCPL (ID, NAME, ENABLED, LOCKED,  PRINCIPAL_TYPE, M_ST, C_ID, C_TS) VALUES (2, 'GROUP ADMINISTRATOR', TRUE, FALSE,  1, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO KPN_USER (ID, REALNAME, EMAIL, PASSWORD)
VALUES (1, 'System Administrator', 'root@kpn.gov.my', 'abc123');
INSERT INTO KPN_PCPL_ROLE (ID, PRINCIPAL_ID, ROLE_TYPE, M_ST, C_ID, C_TS) VALUES(1, 1, 0, 1, 1, CURRENT_TIMESTAMP);
INSERT INTO KPN_PCPL_ROLE (ID, PRINCIPAL_ID, ROLE_TYPE, M_ST, C_ID, C_TS) VALUES(2, 1, 1, 1, 1, CURRENT_TIMESTAMP);

-- GROUP
INSERT INTO KPN_GROP (ID) VALUES (2);
INSERT INTO KPN_GROP_MMBR (ID, GROUP_ID, USER_ID, M_ST, C_ID, C_TS) VALUES (1, 2, 1, 1, 1, CURRENT_TIMESTAMP);



